baseURL: 'https://n00bface.github.io/'
languageCode: 'en-us'
title: 'Bishal Shrestha'
theme: 'PaperMod'

params:
  env: production
  title: 'Bishal Shrestha'
  description: 'Backend Developer proficient in PHP, React, and Gutenberg block development, specializing in AI integration (ChatGPT, TogetherAI) and complex payment systems (Paddle, Stripe).'
  author: 'Bishal Shrestha'
  
  # Custom CSS
  customCSS: ['css/custom.css']
  
  # Home page profile
  homeInfoParams:
    Title: 'Bishal Shrestha'
    Content: 'WordPress Plugin Developer'
    Description: 'Backend Developer with over 3 years of experience specializing in WordPress Plugin Development. Highly proficient in PHP, React JS, and Gutenberg block development. Expertise in integrating complex e-commerce features and leveraging AI APIs (ChatGPT, TogetherAI) to automate content and image creation.'
  
  # Social links
  socialIcons:
    - name: github
      url: 'https://github.com/N00BFACE'
    - name: linkedin
      url: 'https://linkedin.com/in/bishal-shrestha-404553274'
    - name: email
      url: 'mailto:bishalkumar45657@gmail.com'
  
  # Show social icons
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: experience
      name: Experience
      url: /experience/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON

